name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:check
        continue-on-error: false

      - name: Run Prettier check
        run: npm run format:check
        continue-on-error: false

      - name: Build project
        run: npm run build
        continue-on-error: false

      - name: Check for console.log statements
        run: |
          if grep -r "console.log" src/ --include="*.js" --include="*.vue"; then
            echo "⚠️  Warning: console.log statements found in source code"
            echo "Consider removing them for production code"
          else
            echo "✅ No console.log statements found"
          fi

      - name: Check for TODO comments
        run: |
          if grep -r "TODO" src/ --include="*.js" --include="*.vue"; then
            echo "📝 TODO comments found:"
            grep -r "TODO" src/ --include="*.js" --include="*.vue"
          else
            echo "✅ No TODO comments found"
          fi

      - name: Check file sizes
        run: |
          echo "📊 File size analysis:"
          find src/ -name "*.vue" -o -name "*.js" | xargs wc -l | sort -nr | head -10

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-files
          path: dist/
          retention-days: 7 