name: Lint and Check Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install ESLint and Vue linting tools
      run: |
        npm install --save-dev eslint
        npm install --save-dev @vue/eslint-config-prettier
        npm install --save-dev eslint-plugin-vue
        npm install --save-dev prettier
        
    - name: Run ESLint
      run: npx eslint src/ --ext .vue,.js --fix
      
    - name: Run Prettier check
      run: npx prettier --check "src/**/*.{vue,js,json,css}"
      
    - name: Build project
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-files
        path: dist/
        retention-days: 1