name: Vue.js Lint & Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install linting tools
      run: |
        npm install --save-dev eslint
        npm install --save-dev eslint-plugin-vue
        npm install --save-dev @vue/eslint-config-prettier
        npm install --save-dev prettier
        
    - name: Create ESLint config
      run: |
        echo '{
          "root": true,
          "env": {
            "node": true,
            "browser": true,
            "es2021": true
          },
          "extends": [
            "plugin:vue/vue3-essential",
            "eslint:recommended",
            "@vue/prettier"
          ],
          "parserOptions": {
            "ecmaVersion": 2021,
            "sourceType": "module"
          },
          "rules": {
            "no-console": "warn",
            "no-debugger": "warn",
            "vue/multi-word-component-names": "off",
            "vue/no-unused-vars": "warn"
          }
        }' > .eslintrc.json
        
    - name: Create Prettier config
      run: |
        echo '{
          "semi": false,
          "singleQuote": true,
          "tabWidth": 2,
          "trailingComma": "none",
          "printWidth": 80
        }' > .prettierrc
        
    - name: Run ESLint
      run: npx eslint src/ --ext .vue,.js --fix
      
    - name: Check code formatting
      run: npx prettier --check "src/**/*.{vue,js,json,css}"
      
    - name: Build project
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.node-version }}
        path: dist/
        retention-days: 7 